import os
import sys
import json
import argparse
import subprocess
import re
from pathlib import Path

def extract_outline_from_markdown(md_text):
    outline = []
    lines = md_text.splitlines()
    for line in lines:
        stripped = line.strip()
        match = re.match(r'^(#{1,4})\s+(.+)$', stripped)
        if match:
            level = len(match.group(1))
            title = match.group(2).strip()
            # Filter out very short or symbol-only headings
            if len(title) > 2 and len(title) < 120:
                outline.append({
                    "title": title,
                    "level": level,
                    "page": 1
                })
        if len(outline) >= 30:
            break
    return outline

def count_words(text):
    words = re.findall(r'\b\w+\b', text)
    return len(words)

def main():
    parser = argparse.ArgumentParser(description="MinerU PDF Parser Worker")
    parser.add_argument("--input", required=True, help="Input PDF file path")
    parser.add_argument("--output-dir", required=True, help="Output directory for results")
    parser.add_argument("--tier", default="flash", choices=["flash", "basic", "standard", "advanced"], help="MinerU parsing tier")
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    out_dir = Path(args.output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if not input_path.exists():
        print(json.dumps({"success": False, "error": f"Input file not found: {input_path}"}))
        sys.exit(1)

    try:
        # Check if mineru-kit is available in current venv or system
        venv_scripts = Path(sys.executable).parent
        mineru_kit_path = venv_scripts / ("mineru-kit.exe" if os.name == "nt" else "mineru-kit")
        cmd_bin = str(mineru_kit_path) if mineru_kit_path.exists() else "mineru-kit"

        # Execute mineru-kit parse
        cmd = [
            cmd_bin,
            "parse",
            str(input_path),
            "-o", str(out_dir),
            "--tier", args.tier
        ]

        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=300
        )

        # Look for the generated markdown file in output dir
        md_files = list(out_dir.glob("**/*.md"))
        if not md_files:
            # Output error details
            err_msg = result.stderr.strip() or result.stdout.strip() or "No markdown output found."
            print(json.dumps({
                "success": False, 
                "error": f"No markdown output generated by MinerU: {err_msg[:400]}"
            }))
            sys.exit(1)

        # Read the primary markdown file (usually largest or matching base name)
        primary_md_file = sorted(md_files, key=lambda f: f.stat().st_size, reverse=True)[0]
        md_content = primary_md_file.read_text(encoding="utf-8", errors="replace")

        outline = extract_outline_from_markdown(md_content)
        total_words = count_words(md_content)

        # Estimate page count from content_list JSON if generated
        page_count = 1
        meta_files = list(out_dir.glob("**/content_list*.json"))
        if meta_files:
            try:
                meta_data = json.loads(meta_files[0].read_text(encoding="utf-8", errors="replace"))
                if isinstance(meta_data, list):
                    pages = {item.get("page_idx") for item in meta_data if "page_idx" in item}
                    if pages:
                        page_count = max(pages) + 1
            except Exception:
                pass

        output_data = {
            "success": True,
            "markdown": md_content,
            "outline": outline if outline else [{"title": "Tài liệu bóc tách bởi MinerU", "level": 1, "page": 1}],
            "pageCount": page_count,
            "totalWords": total_words,
            "outputFile": str(primary_md_file)
        }

        print(json.dumps(output_data, ensure_ascii=False))

    except subprocess.TimeoutExpired:
        print(json.dumps({"success": False, "error": "MinerU parse process timed out (> 300s)"}))
        sys.exit(1)
    except Exception as e:
        print(json.dumps({"success": False, "error": str(e)}))
        sys.exit(1)

if __name__ == "__main__":
    main()
